"""Deterministic synthetic image-classification dataset.

Images make the small-file problem visible and let the tutorial separate
file-open overhead, byte reading, and decoding. The dataset is generated by the
learner rather than stored in Git.

Determinism
-----------
Each sample is seeded from ``(seed, index)`` alone, so a sample's bytes do not
depend on generation order or on how many processes did the work. Regenerating
with the same profile therefore reproduces the same checksums and the same
manifest, byte for byte, for a given Pillow version. Pillow encodes
deterministically, but a different Pillow release may emit different bytes; the
manifest records checksums so a mismatch is detected rather than assumed away.
"""

from __future__ import annotations

import io
import json
import os
from concurrent.futures import ProcessPoolExecutor
from dataclasses import asdict, dataclass, fields
from pathlib import Path
from typing import Any, Iterator, Sequence

import numpy as np
from PIL import Image

from .manifest import Sample, checksum_bytes, write_manifest

#: Resolution of the low-frequency colour field before upsampling. Small enough
#: that images have large smooth regions, which is what makes JPEG sizes vary.
_COARSE = 8


@dataclass(frozen=True)
class Profile:
    """Generation parameters for one dataset profile."""

    profile: str
    samples: int
    width: int
    height: int
    encoding: str = "jpeg"
    classes: int = 100
    seed: int = 1234
    #: Pixel noise amplitude (0-255). Higher values compress worse, producing
    #: larger files and more decode work.
    noise: int = 24
    jpeg_quality: int = 85
    png_compress_level: int = 6

    @classmethod
    def from_mapping(cls, data: Any, source: str = "<dict>") -> "Profile":
        if not isinstance(data, dict):
            raise ValueError(f"{source}: dataset profile must be a mapping")
        known = {f.name for f in fields(cls)}
        unknown = set(data) - known
        if unknown:
            raise ValueError(
                f"{source}: unknown dataset profile field(s) {sorted(unknown)}; "
                f"known fields are {sorted(known)}"
            )
        for required in ("profile", "samples", "width", "height"):
            if required not in data:
                raise ValueError(f"{source}: dataset profile is missing '{required}'")
        profile = cls(**data)
        profile.validate(source)
        return profile

    def validate(self, source: str = "<profile>") -> None:
        if self.samples < 1:
            raise ValueError(f"{source}: samples must be >= 1")
        if self.width < 1 or self.height < 1:
            raise ValueError(f"{source}: width and height must be >= 1")
        if self.classes < 1:
            raise ValueError(f"{source}: classes must be >= 1")
        if self.encoding not in ("jpeg", "png"):
            raise ValueError(f"{source}: encoding must be 'jpeg' or 'png'")
        if not 0 <= self.noise <= 255:
            raise ValueError(f"{source}: noise must be in [0, 255]")
        if not 1 <= self.jpeg_quality <= 100:
            raise ValueError(f"{source}: jpeg_quality must be in [1, 100]")
        if not 0 <= self.png_compress_level <= 9:
            raise ValueError(f"{source}: png_compress_level must be in [0, 9]")

    @property
    def extension(self) -> str:
        return "jpg" if self.encoding == "jpeg" else "png"


#: Built-in profiles. ``tiny`` exists so that the whole pipeline can be exercised
#: on a laptop in seconds; the other three are the profiles described in the
#: tutorial plan.
PROFILES: dict[str, Profile] = {
    "tiny": Profile(
        profile="tiny", samples=256, width=32, height=32, encoding="jpeg", classes=8
    ),
    "metadata-heavy": Profile(
        profile="metadata-heavy", samples=50_000, width=64, height=64, encoding="jpeg"
    ),
    "balanced": Profile(
        profile="balanced", samples=20_000, width=224, height=224, encoding="jpeg"
    ),
    "decode-heavy": Profile(
        profile="decode-heavy",
        samples=10_000,
        width=1024,
        height=1024,
        encoding="png",
        noise=48,
    ),
}


def load_profile(path: str | os.PathLike[str]) -> Profile:
    """Load a profile from a YAML file with a top-level ``dataset:`` mapping."""
    import yaml

    path = Path(path)
    raw = yaml.safe_load(path.read_text())
    if not isinstance(raw, dict) or "dataset" not in raw:
        raise ValueError(f"{path}: expected a top-level 'dataset' mapping")
    unknown = set(raw) - {"dataset"}
    if unknown:
        raise ValueError(f"{path}: unknown top-level key(s) {sorted(unknown)}")
    return Profile.from_mapping(raw["dataset"], source=str(path))


def sample_id_for(index: int) -> str:
    return f"s{index:08d}"


def relative_path_for(profile: Profile, index: int) -> str:
    class_id = index % profile.classes
    return f"images/class_{class_id:04d}/{sample_id_for(index)}.{profile.extension}"


def encode_sample(profile: Profile, index: int) -> bytes:
    """Render and encode one sample. Depends only on the profile and the index."""
    rng = np.random.default_rng([profile.seed, index])
    class_id = index % profile.classes

    # Low-frequency colour field, upsampled. Gives large smooth regions.
    coarse = rng.integers(0, 256, size=(_COARSE, _COARSE, 3), dtype=np.uint8)
    base = np.asarray(
        Image.fromarray(coarse).resize((profile.width, profile.height), Image.BILINEAR),
        dtype=np.float32,
    )

    # A per-class colour tint plus a per-class block, so the dataset is nominally
    # learnable and a wrong class assignment is visible by eye.
    tint = _class_tint(class_id, profile.classes)
    pixels = 0.7 * base + 0.3 * tint
    _stamp_class_block(pixels, class_id, profile)

    if profile.noise:
        pixels += rng.normal(0.0, profile.noise, size=pixels.shape)

    image = Image.fromarray(np.clip(pixels, 0, 255).astype(np.uint8), mode="RGB")
    buffer = io.BytesIO()
    if profile.encoding == "jpeg":
        image.save(buffer, format="JPEG", quality=profile.jpeg_quality, optimize=False)
    else:
        image.save(buffer, format="PNG", compress_level=profile.png_compress_level)
    return buffer.getvalue()


def generate_dataset(
    profile: Profile,
    output_dir: str | os.PathLike[str],
    manifest_path: str | os.PathLike[str] | None = None,
    workers: int = 1,
    overwrite: bool = False,
    progress_every: int = 0,
) -> Path:
    """Write the dataset and its manifest. Returns the manifest path.

    ``workers`` parallelises encoding only; the manifest is assembled in index
    order, so the result does not depend on the worker count.
    """
    profile.validate()
    output_dir = Path(output_dir)
    manifest_path = (
        Path(manifest_path) if manifest_path else output_dir / "manifest.jsonl"
    )

    if output_dir.exists() and any(output_dir.iterdir()) and not overwrite:
        raise FileExistsError(
            f"{output_dir} is not empty; pass --overwrite to regenerate it"
        )
    for class_id in range(min(profile.classes, profile.samples)):
        (output_dir / f"images/class_{class_id:04d}").mkdir(parents=True, exist_ok=True)

    samples: list[Sample] = []
    for index, payload in _encoded_payloads(profile, workers):
        relative = relative_path_for(profile, index)
        target = output_dir / relative
        target.write_bytes(payload)
        samples.append(
            Sample(
                sample_id=sample_id_for(index),
                relative_path=relative,
                class_id=index % profile.classes,
                byte_size=len(payload),
                width=profile.width,
                height=profile.height,
                checksum=checksum_bytes(payload),
                # Work proxy for shard balancing: pixels to decode, not seconds.
                estimated_decode_cost=profile.width * profile.height,
            )
        )
        if progress_every and len(samples) % progress_every == 0:
            print(f"generated {len(samples)}/{profile.samples} samples", flush=True)

    write_manifest(manifest_path, samples)
    _write_profile_record(output_dir, profile, manifest_path, samples)
    return manifest_path


def _encoded_payloads(profile: Profile, workers: int) -> Iterator[tuple[int, bytes]]:
    indices = range(profile.samples)
    if workers <= 1:
        for index in indices:
            yield index, encode_sample(profile, index)
        return
    # chunksize keeps per-task overhead small for the many-small-images profiles.
    chunksize = max(1, profile.samples // (workers * 8))
    with ProcessPoolExecutor(max_workers=workers) as pool:
        payloads = pool.map(_encode_one, ((profile, i) for i in indices), chunksize=chunksize)
        for index, payload in zip(indices, payloads):
            yield index, payload


def _encode_one(args: tuple[Profile, int]) -> bytes:
    profile, index = args
    return encode_sample(profile, index)


def _class_tint(class_id: int, classes: int) -> np.ndarray:
    """Deterministic RGB tint spread over the hue circle."""
    angle = 2.0 * np.pi * (class_id / classes)
    return np.array(
        [
            127.5 * (1.0 + np.sin(angle)),
            127.5 * (1.0 + np.sin(angle + 2.0 * np.pi / 3.0)),
            127.5 * (1.0 + np.sin(angle + 4.0 * np.pi / 3.0)),
        ],
        dtype=np.float32,
    )


def _stamp_class_block(pixels: np.ndarray, class_id: int, profile: Profile) -> None:
    """Draw a bright block whose position encodes the class. Modifies in place."""
    grid = max(1, int(np.ceil(np.sqrt(profile.classes))))
    cell_h = max(1, profile.height // grid)
    cell_w = max(1, profile.width // grid)
    row, col = divmod(class_id, grid)
    top = min(row * cell_h, profile.height - cell_h)
    left = min(col * cell_w, profile.width - cell_w)
    pixels[top : top + cell_h, left : left + cell_w] = 255.0 - _class_tint(
        class_id, profile.classes
    )


def _write_profile_record(
    output_dir: Path,
    profile: Profile,
    manifest_path: Path,
    samples: Sequence[Sample],
) -> None:
    """Record how the dataset was produced, next to the dataset itself."""
    record = {
        "dataset": asdict(profile),
        "manifest_path": str(manifest_path),
        "total_samples": len(samples),
        "total_bytes": sum(sample.byte_size for sample in samples),
    }
    (output_dir / "dataset_profile.json").write_text(
        json.dumps(record, indent=2, sort_keys=True) + "\n"
    )
